import React, { useEffect, useMemo, useState } from "react";
import { Trophy, Flag, Wrench, Users, DollarSign, Star, Gauge, Building2, Activity, Wind, Zap, Lock, UserPlus, FastForward, Newspaper, Save, RotateCcw, CloudRain, ShieldCheck, CircleDot, Flame, Medal, Radio, Timer, Car, Crown, Sparkles, Target, Cpu, Handshake, BarChart3, Settings } from "lucide-react";
import { LineChart, Line, XAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";

const money = (n) => `${n < 0 ? "-" : ""}$${Math.abs(Math.round(n)).toLocaleString()}`;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const pick = (a) => a[Math.floor(Math.random() * a.length)];
const uid = () => Math.random().toString(36).slice(2, 10);

const CARS = [
  { id:"hatch", name:"Street Hatch", price:22000, tier:1, speed:33, grip:38, reliability:68, render:"compact" },
  { id:"coupe", name:"Club Coupe", price:56000, tier:1, speed:45, grip:48, reliability:62, render:"coupe" },
  { id:"gt4", name:"GT4 Contender", price:135000, tier:2, speed:62, grip:65, reliability:57, render:"gt" },
  { id:"gt3", name:"GT3 Works", price:310000, tier:3, speed:78, grip:80, reliability:51, render:"gt3" },
  { id:"proto", name:"Prototype X", price:760000, tier:4, speed:93, grip:92, reliability:44, render:"prototype" },
];
const SERIES = [
  { id:1, name:"Local Cup", rep:0, races:6, power:38, entry:700, prize:[6000,3300,1800,900,400], fans:250 },
  { id:2, name:"Regional GT", rep:80, races:8, power:55, entry:2400, prize:[18000,10000,5800,2600,900], fans:650 },
  { id:3, name:"National Championship", rep:210, races:10, power:72, entry:8500, prize:[62000,35000,19000,9000,3500], fans:1600 },
  { id:4, name:"World Endurance", rep:430, races:12, power:88, entry:21000, prize:[175000,95000,52000,25000,9000], fans:4200 },
];
const TRACKS = ["Greenfield Oval", "Harbor Sprint", "Canyon Pass", "Sunset Speedway", "Mountain GP", "Velocity Park", "Monte Azure", "Desert Apex", "Global Endurance", "Apex Masters"];
const WEATHER = [
  { name:"Clear", icon:"☀️", grip:1, reliability:1, drama:0.08 },
  { name:"Cloudy", icon:"☁️", grip:.99, reliability:1, drama:0.10 },
  { name:"Light Rain", icon:"🌧️", grip:.91, reliability:.98, drama:0.18 },
  { name:"Heavy Rain", icon:"⛈️", grip:.82, reliability:.94, drama:0.28 },
  { name:"Hot Track", icon:"🔥", grip:.96, reliability:.91, drama:0.20 },
];
const TRAITS = [
  { name:"Aggressive", speed:5, grip:-2, risk:.07, desc:"fast but crash-prone" },
  { name:"Smooth", speed:0, grip:5, risk:-.05, desc:"protects tires" },
  { name:"Rain Master", speed:0, grip:9, risk:-.03, wet:true, desc:"elite in wet weather" },
  { name:"Qualifier", speed:7, grip:0, risk:.02, quali:true, desc:"great over one lap" },
  { name:"Fan Favorite", speed:1, grip:1, risk:0, fans:.18, desc:"boosts fan growth" },
  { name:"Reliable", speed:-1, grip:1, risk:-.09, desc:"rarely makes mistakes" },
];
const SPONSORS = [
  { name:"Redline Energy", req:0, pay:900, bonus:4500, goal:"Finish Top 5", rep:5 },
  { name:"Apex Oil", req:60, pay:2200, bonus:11000, goal:"Finish Top 3", rep:10 },
  { name:"Velocity Bank", req:180, pay:6400, bonus:30000, goal:"Win", rep:20 },
  { name:"Titan Hyperworks", req:390, pay:17000, bonus:85000, goal:"Podium", rep:35 },
];
const TEAMS = ["Ironclad Racing","Crimson Apex","Falcon Wing","Northbound","Stormfront","Obsidian","Aurora Velocity","Pinnacle","Redline Syndicate","Lighthouse Racing"];
const NAMES = ["Jamie Cole","Alex Reyes","Sofia Silva","Kenji Tanaka","Morgan Voss","Priya Park","Marco Russo","Riley Hartman","Nadia Klein","Theo Delgado","Omar Ibrahim","Elena Moreau"];

function driver(seed=0){ const tr=pick(TRAITS); const skill=clamp(Math.round(42+Math.random()*38+seed),38,96); const calm=clamp(Math.round(40+Math.random()*42),35,95); return {id:uid(),name:pick(NAMES),skill,calm,trait:tr,salary:Math.round(420+skill*13+calm*5),age:18+Math.floor(Math.random()*18),xp:0};}
function baseGame(){return {cash:85000,week:1,rep:0,fans:300,season:1,raceNo:1,championship:[],history:[{week:1,cash:85000}],sponsor:SPONSORS[0],tab:"home",hq:{garage:1,rd:0,marketing:0,staff:0},cars:[{id:"starter",model:"hatch",name:"Hatchling #1",condition:100,up:{engine:0,tires:0,aero:0,reliability:0},driverId:"starterDriver",paint:"amber"}],drivers:[{...driver(),id:"starterDriver",name:"Jamie Cole",skill:50,calm:54,salary:420,trait:TRAITS[5]}],candidates:[driver(),driver(),driver()],selected:"starter",log:["Apex Tycoon v1 started. Build the garage, sign sponsors, and chase championships."],records:{wins:0,poles:0,podiums:0,titles:0}}}
function carStats(car){ const m=CARS.find(c=>c.id===car.model); return {speed:m.speed+car.up.engine*8+car.up.aero*3,grip:m.grip+car.up.tires*8+car.up.aero*4,reliability:clamp(m.reliability+car.up.reliability*10+car.condition*.18,5,99),model:m};}
function title(rep){ if(rep<80)return"Garage Rookie"; if(rep<210)return"Club Principal"; if(rep<430)return"National Contender"; if(rep<800)return"World Class Team"; return"Motorsport Dynasty";}

function saveGame(g){ localStorage.setItem("apexTycoonV1", JSON.stringify(g)); }
function loadGame(){ try{return JSON.parse(localStorage.getItem("apexTycoonV1"))||baseGame()}catch{return baseGame()} }

function Stat({label,value,max=100,icon:Icon}){return <div className="stat"><div><span>{Icon&&<Icon size={13}/>} {label}</span><b>{Math.round(value)}</b></div><i><em style={{width:`${clamp(value/max*100,0,100)}%`}}/></i></div>}
function Card({children, className=""}){return <section className={`card ${className}`}>{children}</section>}
function CarRender({type="compact",weather="Clear",paint="amber"}){return <div className={`scene ${weather.includes("Rain")?"rain":""}`}><div className="garageLights"/><div className="floorGrid"/><div className={`carRender ${type} ${paint}`}><span className="shadow"/><span className="body"/><span className="hood"/><span className="roof"/><span className="wing"/><span className="wheel w1"/><span className="wheel w2"/><span className="glow"/></div><div className="toolbox"/><div className="lift"/></div>}
function Header({g,setG}){return <header><div className="brand"><div className="logo"><Flag size={18}/></div><div><h1>Apex Tycoon</h1><p>{title(g.rep)} • Season {g.season}</p></div></div><div className="week"><small>WEEK</small><b>{g.week}</b></div><div className="pills"><div><DollarSign size={14}/><span>{money(g.cash)}</span></div><div><Trophy size={14}/><span>{g.rep} REP</span></div><div><Star size={14}/><span>{g.fans.toLocaleString()}</span></div></div><nav>{[["home",Gauge],["garage",Wrench],["drivers",Users],["race",Flag],["hq",Building2],["stats",BarChart3]].map(([id,Icon])=><button key={id} onClick={()=>setG({...g,tab:id})} className={g.tab===id?"on":""}><Icon size={15}/>{id}</button>)}</nav></header>}

export default function App(){
 const [g,setG]=useState(loadGame); const [race,setRace]=useState(null); const [anim,setAnim]=useState(0);
 useEffect(()=>saveGame(g),[g]);
 useEffect(()=>{ if(!race||race.phase!=="live")return; const t=setInterval(()=>setAnim(v=>{ if(v>=100){clearInterval(t); setRace(r=>({...r,phase:"result"})); return 100} return v+2.5+Math.random()*3}),120); return()=>clearInterval(t)},[race]);
 const selected=g.cars.find(c=>c.id===g.selected)||g.cars[0]; const selectedDriver=g.drivers.find(d=>d.id===selected?.driverId); const series=SERIES.slice().reverse().find(s=>g.rep>=s.rep)||SERIES[0]; const slots=1+g.hq.garage;
 const addLog=(m)=>setG(x=>({...x,log:[m,...x.log].slice(0,10)}));
 function simRace(){ if(!selected||!selectedDriver){addLog("Assign a driver before racing.");return} if(g.cash<series.entry){addLog("Not enough cash for entry fee.");return} const weather=pick(WEATHER), track=pick(TRACKS); const st=carStats(selected); const wet=weather.name.includes("Rain"); const trait=selectedDriver.trait; const qualiPower=st.speed*.45+st.grip*.25+selectedDriver.skill*.3+(trait.quali?8:0)+(Math.random()*20-10); const opponents=Array.from({length:9},(_,i)=>({id:uid(),name:TEAMS[i],team:true,points:0,power:series.power+(Math.random()*28-14)})); const grid=[{id:"player",name:`${selected.name} / ${selectedDriver.name}`,player:true,power:qualiPower},...opponents].sort((a,b)=>b.power-a.power); const pole=grid[0].player; let racePower=st.speed*.34+st.grip*.33*weather.grip+selectedDriver.skill*.21+selectedDriver.calm*.12+(trait.speed||0)+(trait.grip||0)+(wet&&trait.wet?12:0)+(Math.random()*24-12); const risk=clamp(.07+weather.drama+(trait.risk||0)+(100-st.reliability)*.006,0,.48); const dnf=Math.random()<risk; if(dnf) racePower=-999; const field=[{id:"player",name:`${selected.name} / ${selectedDriver.name}`,player:true,power:racePower,dnf},...opponents.map(o=>({...o,power:o.power+Math.random()*18-9}))].sort((a,b)=>b.power-a.power); const rank=field.findIndex(f=>f.player); const events=[]; if(pole)events.push("TV cameras caught your car taking pole in qualifying."); if(weather.name.includes("Rain"))events.push(`${weather.icon} ${weather.name} turned strategy into a gamble.`); if(Math.random()<weather.drama)events.push("A safety car compressed the field halfway through the race."); if(dnf)events.push("A mechanical issue ended the race early."); else if(rank===0)events.push("Your pit wall nailed the strategy and controlled the final stint."); else if(rank<3)events.push("A clean podium finish impressed the paddock."); else events.push("The team brought the car home and collected useful data."); setAnim(0); setRace({phase:"live",weather,track,grid,field,rank,dnf,pole,events}); }
 function collect(){ if(!race)return; const rank=race.rank; const prize=race.dnf?0:(series.prize[rank]||500); const sponsor=g.sponsor; let sponsorBonus=sponsor.pay; const goalMet=(!race.dnf)&&((sponsor.goal.includes("Win")&&rank===0)||(sponsor.goal.includes("Top 3")&&rank<3)||(sponsor.goal.includes("Top 5")&&rank<5)||(sponsor.goal.includes("Podium")&&rank<3)); if(goalMet)sponsorBonus+=sponsor.bonus; const traitFans=selectedDriver.trait.fans?1.18:1; const repGain=race.dnf?-4:Math.max(2,Math.round((series.races-rank)*2.4)); const fanGain=race.dnf?-90:Math.round(series.fans*Math.max(.15,1-rank/10)*traitFans*(1+g.hq.marketing*.15)); const loss=clamp(7+Math.random()*14+(race.dnf?14:0),4,35); const points=[25,18,15,12,10,8,6,4,2,1][rank]||0; const nextChamp=[...g.championship,{season:g.season,race:g.raceNo,track:race.track,points,position:rank+1}]; let newRaceNo=g.raceNo+1, newSeason=g.season, newRecords={...g.records}; if(rank===0)newRecords.wins++; if(rank<3&&!race.dnf)newRecords.podiums++; if(race.pole)newRecords.poles++; let logs=[`Finished ${race.dnf?"DNF":`P${rank+1}`} at ${race.track}. Cash change ${money(prize+sponsorBonus-series.entry-selectedDriver.salary)}.`]; let seasonDone=newRaceNo>series.races; if(seasonDone){ const total=nextChamp.filter(r=>r.season===g.season).reduce((s,r)=>s+r.points,0); if(total>series.races*12){newRecords.titles++; logs.unshift(`🏆 Season ${g.season} title secured with ${total} points!`)} else logs.unshift(`Season ${g.season} complete with ${total} points.`); newSeason++; newRaceNo=1; }
 setG(x=>({...x,cash:x.cash+prize+sponsorBonus-series.entry-selectedDriver.salary,week:x.week+1,season:newSeason,raceNo:newRaceNo,rep:clamp(x.rep+repGain,0,9999),fans:clamp(x.fans+fanGain,0,9999999),championship:nextChamp,records:newRecords,history:[...x.history,{week:x.week+1,cash:x.cash+prize+sponsorBonus-series.entry-selectedDriver.salary}].slice(-40),cars:x.cars.map(c=>c.id===selected.id?{...c,condition:clamp(c.condition-loss,5,100)}:c),drivers:x.drivers.map(d=>d.id===selectedDriver.id?{...d,xp:d.xp+points,skill:clamp(d.skill+(points>12?1:0),1,99)}:d),log:[...logs,...race.events,...x.log].slice(0,10)})); setRace(null); }
 function upgrade(car,type){ const cost=Math.round((CARS.find(c=>c.id===car.model).price*.06)*(car.up[type]+1)*(1.25**car.up[type])*(1-g.hq.rd*.06)); if(car.up[type]>=5)return; if(g.cash<cost){addLog("Not enough cash for that upgrade.");return} setG(x=>({...x,cash:x.cash-cost,cars:x.cars.map(c=>c.id===car.id?{...c,up:{...c.up,[type]:c.up[type]+1}}:c),log:[`Installed ${type} level ${car.up[type]+1} on ${car.name}.`,...x.log].slice(0,10)})); }
 function buy(model){ const m=CARS.find(c=>c.id===model); if(g.cars.length>=slots){addLog("Garage full. Upgrade HQ garage bays.");return} if(g.cash<m.price){addLog("Not enough cash for that car.");return} const car={id:uid(),model,name:`${m.name} #${g.cars.length+1}`,condition:100,up:{engine:0,tires:0,aero:0,reliability:0},driverId:null,paint:pick(["amber","blue","red","silver"])}; setG({...g,cash:g.cash-m.price,cars:[...g.cars,car],selected:car.id,log:[`Purchased ${m.name}.`,...g.log].slice(0,10)}); }
 function hire(d){ const fee=d.salary*4; if(g.cash<fee){addLog("Not enough cash to sign driver.");return} setG({...g,cash:g.cash-fee,drivers:[...g.drivers,d],candidates:g.candidates.filter(c=>c.id!==d.id),log:[`Signed ${d.name}, a ${d.trait.name} driver.`,...g.log].slice(0,10)}); }
 const content = race? <RaceView race={race} anim={anim} collect={collect} skip={()=>{setAnim(100);setRace({...race,phase:"result"})}}/> : g.tab==="home"? <Home g={g} series={series} setTab={(t)=>setG({...g,tab:t})}/> : g.tab==="garage"? <Garage g={g} setG={setG} selected={selected} slots={slots} upgrade={upgrade} buy={buy}/> : g.tab==="drivers"? <Drivers g={g} setG={setG} hire={hire}/> : g.tab==="race"? <RaceSetup g={g} setG={setG} selected={selected} driver={selectedDriver} series={series} simRace={simRace}/> : g.tab==="hq"? <HQ g={g} setG={setG}/> : <Stats g={g} setG={setG}/>;
 return <div className="app"><Header g={g} setG={setG}/><main>{content}</main><footer><button onClick={()=>{saveGame(g);addLog("Game saved.")}}><Save size={14}/> Save</button><button onClick={()=>{if(confirm("Reset Apex Tycoon save?")){localStorage.removeItem("apexTycoonV1");setG(baseGame());}}}><RotateCcw size={14}/> Reset</button></footer></div>
}
function Home({g,series,setTab}){return <div className="stack"><CarRender type={(CARS.find(c=>c.id===g.cars[0].model)||CARS[0]).render} paint={g.cars[0].paint}/><Card><div className="cardTitle"><Trending/> Team Command Center</div><div className="biggrid"><button onClick={()=>setTab("race")} className="primary"><Flag/> Race Weekend</button><button onClick={()=>setTab("garage")}><Wrench/> Build Cars</button><button onClick={()=>setTab("drivers")}><Users/> Sign Drivers</button><button onClick={()=>setTab("hq")}><Building2/> Upgrade HQ</button></div></Card><Card><div className="cardTitle"><Trophy size={15}/> Current Series</div><h2>{series.name}</h2><p>Race {g.raceNo}/{series.races} • Entry {money(series.entry)} • Win pays {money(series.prize[0])}</p><div className="progress"><span style={{width:`${g.raceNo/series.races*100}%`}}/></div></Card><Card><div className="cardTitle"><Activity size={15}/> Cash Trend</div><div className="chart"><ResponsiveContainer><LineChart data={g.history}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="week" tick={{fill:"#7d8796",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip formatter={(v)=>money(v)} contentStyle={{background:"#0b0f16",border:"1px solid rgba(255,176,32,.35)",borderRadius:12}}/><Line dataKey="cash" stroke="#ffb020" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></Card><Card><div className="cardTitle"><Newspaper size={15}/> Team News</div>{g.log.map((l,i)=><p key={i} className={i?'news':'news hot'}>{l}</p>)}</Card></div>}
function Trending(){return <Flame size={15}/>}
function Garage({g,setG,selected,slots,upgrade,buy}){return <div className="stack"><CarRender type={carStats(selected).model.render} paint={selected.paint}/><Card><div className="cardTitle"><Car size={15}/> Garage {g.cars.length}/{slots}</div><select value={selected.id} onChange={e=>setG({...g,selected:e.target.value})}>{g.cars.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Stat label="Speed" icon={Zap} value={carStats(selected).speed} max={130}/><Stat label="Grip" icon={CircleDot} value={carStats(selected).grip} max={130}/><Stat label="Reliability" icon={ShieldCheck} value={carStats(selected).reliability} max={100}/><Stat label="Condition" icon={Activity} value={selected.condition} max={100}/><div className="grid2">{["engine","tires","aero","reliability"].map(t=><button key={t} onClick={()=>upgrade(selected,t)}><Settings size={14}/>{t} Lv {selected.up[t]}/5</button>)}</div></Card><Card><div className="cardTitle"><Sparkles size={15}/> Dealer Lot</div>{CARS.map(c=><button className="row" key={c.id} onClick={()=>buy(c.id)}><span>{c.name}<small> SPD {c.speed} GRIP {c.grip}</small></span><b>{money(c.price)}</b></button>)}</Card></div>}
function Drivers({g,setG,hire}){return <div className="stack"><Card><div className="cardTitle"><Users size={15}/> Roster</div>{g.drivers.map(d=><div className="driver" key={d.id}><div><b>{d.name}</b><small>{d.age} yrs • {d.trait.name}: {d.trait.desc}</small></div><Stat label="Skill" value={d.skill} icon={Star}/><Stat label="Calm" value={d.calm} icon={Activity}/><select value={g.cars.find(c=>c.driverId===d.id)?.id||""} onChange={e=>setG({...g,cars:g.cars.map(c=>c.id===e.target.value?{...c,driverId:d.id}:c.driverId===d.id?{...c,driverId:null}:c)})}><option value="">Bench</option>{g.cars.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>)}</Card><Card><div className="cardTitle"><Target size={15}/> Scouted Talent</div>{g.candidates.map(d=><button className="row" key={d.id} onClick={()=>hire(d)}><span>{d.name}<small>{d.trait.name} • Skill {d.skill} • Calm {d.calm}</small></span><b><UserPlus size={13}/> {money(d.salary*4)}</b></button>)}<button onClick={()=>setG({...g,candidates:[driver(g.hq.staff*5),driver(g.hq.staff*5),driver(g.hq.staff*5)]})}><FastForward size={14}/> Re-scout</button></Card></div>}
function RaceSetup({g,setG,selected,driver,series,simRace}){return <div className="stack"><CarRender type={carStats(selected).model.render} paint={selected.paint}/><Card className="raceCard"><div className="cardTitle"><Radio size={15}/> Race Weekend</div><h2>{series.name}</h2><p>Selected: <b>{selected.name}</b> with <b>{driver?driver.name:"No Driver"}</b></p><select value={g.selected} onChange={e=>setG({...g,selected:e.target.value})}>{g.cars.map(c=><option key={c.id} value={c.id}>{c.name} {c.driverId?"":"— no driver"}</option>)}</select><div className="grid2"><div><CloudRain/> Dynamic weather</div><div><Timer/> Qualifying</div><div><Cpu/> Strategy events</div><div><Handshake/> Sponsor goals</div></div><button className="primary giant" onClick={simRace}><Flag/> Start Race Weekend</button></Card><Card><div className="cardTitle"><Handshake size={15}/> Sponsor</div><h2>{g.sponsor.name}</h2><p>{money(g.sponsor.pay)}/week • Bonus {money(g.sponsor.bonus)} • Goal: {g.sponsor.goal}</p>{SPONSORS.filter(s=>g.rep>=s.req).map(s=><button className="row" key={s.name} onClick={()=>setG({...g,sponsor:s})}><span>{s.name}<small>{s.goal}</small></span><b>{money(s.pay)}/wk</b></button>)}</Card></div>}
function HQ({g,setG}){const defs={garage:["Garage Bays",60000],rd:["R&D Lab",75000],marketing:["Marketing Office",65000],staff:["Scouting Dept",70000]};return <div className="stack"><CarRender type="prototype"/><Card><div className="cardTitle"><Building2 size={15}/> Headquarters</div>{Object.entries(defs).map(([k,[name,cost]])=><button className="row" key={k} onClick={()=>{let real=Math.round(cost*(g.hq[k]+1)); if(g.cash>=real)setG({...g,cash:g.cash-real,hq:{...g.hq,[k]:g.hq[k]+1},log:[`${name} upgraded to level ${g.hq[k]+2}.`,...g.log].slice(0,10)})}}><span>{name}<small>Level {g.hq[k]+1}</small></span><b>{money(cost*(g.hq[k]+1))}</b></button>)}</Card></div>}
function Stats({g,setG}){const pts=g.championship.filter(r=>r.season===g.season).reduce((s,r)=>s+r.points,0);return <div className="stack"><Card><div className="cardTitle"><Crown size={15}/> Records</div><div className="records"><div><b>{g.records.wins}</b><small>Wins</small></div><div><b>{g.records.podiums}</b><small>Podiums</small></div><div><b>{g.records.poles}</b><small>Poles</small></div><div><b>{g.records.titles}</b><small>Titles</small></div></div></Card><Card><div className="cardTitle"><Medal size={15}/> Season {g.season}</div><h2>{pts} points</h2>{g.championship.filter(r=>r.season===g.season).map(r=><p className="news" key={r.race}>Race {r.race}: P{r.position} at {r.track} • {r.points} pts</p>)}</Card></div>}
function RaceView({race,anim,collect,skip}){return <div className="stack"><Card className="raceLive"><div className="cardTitle"><Flag size={15}/> {race.track} • {race.weather.icon} {race.weather.name}</div>{race.phase==="live"?<><div className="track"><div className="trackOval"><span className="carDot player" style={{offsetDistance:`${anim}%`}}/><span className="carDot rival r1" style={{offsetDistance:`${Math.max(0,anim-6)}%`}}/><span className="carDot rival r2" style={{offsetDistance:`${Math.max(0,anim-13)}%`}}/></div></div><div className="leaderboard">{race.field.slice(0,6).map((f,i)=><p key={f.id}><b>P{i+1}</b> {f.name}</p>)}</div><button onClick={skip}><FastForward size={14}/> Skip to Results</button></>:<><div className="resultBadge">{race.dnf?"DNF":`P${race.rank+1}`}</div><div className="leaderboard">{race.field.map((f,i)=><p className={f.player?"me":""} key={f.id}><b>P{i+1}</b> {f.name} {f.dnf?"DNF":""}</p>)}</div>{race.events.map(e=><p className="news hot" key={e}>{e}</p>)}<button className="primary giant" onClick={collect}>Continue</button></>}</Card></div>}
